Add timeToMergeFromFirstReviewSeconds
shibayu36/merged-pr-stat pull request #11
Opened 2021-11-17 17:04 UTC by odanado

Thank you for a great cli.

timeToMergeFromFirstReviewSeconds: seconds between a first review  and a PullRequest merged.
timeToMergeFromFirstReviewSeconds represents the time spent reviewing the pull request.

This allows for a more detailed analysis of the lead time breakdown.

2021-11-27 11:50 UTC, shibayu36 requested changes
It's good fields to understand productivity.  I suggested to fix README.md

2021-11-27 11:50 UTC, shibayu36 commented on README.md
> +* timeToMergeFromFirstReviewSecondsMedian: the median of seconds between a first review  and a PullRequest merged.
Please add these fields to json sample above

2021-12-07 16:58 UTC, odanado commented
@shibayu36 I have fixed the README. Could you re-review.

2021-12-11 02:27 UTC, shibayu36 approved these changes
Great! LGTM

2021-12-11 02:27 UTC, merged

2021-12-11 02:39 UTC, shibayu36 commented
I have just released it as 0.3.0
https://www.npmjs.com/package/@shibayu36/merged-pr-stat

Thanks for your pull request